# Generated by Django 3.2.9 on 2021-11-25 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shoptype', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('phno', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('pendingitems', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shopmanagerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ItemQuerry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=500)),
                ('pending', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('appoinment', models.CharField(max_length=50, null=True)),
                ('notes', models.CharField(max_length=500, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopmanager.shop')),
            ],
        ),
    ]
