# Generated by Django 3.2.9 on 2021-11-25 16:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('community_type', models.CharField(choices=[('Open Community', 'Open Community'), ('Quarantine Community', 'Quarantine Community'), ('Lockdown Stuck Community', 'Lockdown Stuck Community')], default='Open Community', max_length=50)),
                ('content', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('likes_count', models.IntegerField(default=0)),
                ('dislikes_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=250, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writter', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=250)),
                ('posting_time', models.DateTimeField(default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.post')),
            ],
        ),
    ]
